# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-23 01:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clients', models.CharField(max_length=128, verbose_name='客户端号')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000)])),
            ],
        ),
    ]
